stages:
  - build
  - test

variables:
  GIT_STRATEGY: none

build:
  stage: build
  tags:
    - csl-176
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cd $BLOG_RUNNER_PATH
    - ./runner.sh sync core_package
    - ./runner.sh build_admin install

analyse:
  stage: test
  image: composer
  tags:
    - csl-176
  before_script:
    - php -v
    - composer --version
  script:
    - composer install --prefer-dist --no-progress
    - composer a
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' || $CI_PIPELINE_SOURCE == 'merge_request_event'
